### ISSUE TITLE
Using Oracle in place of Postgres for fonduer

### ISSUE THREAD

**Issue by Prabh06** [HazyResearch/fonduer#129]
**Is your feature request related to a problem? Please describe.**
I have an Oracle instance, and, want to use it instead of Postgres.

**Describe the solution you'd like**
What all changes are required to make the switch, and, is there an existing config/notes that can help to make the change. From my understanding the Alchemy supports both and we have to just make sure any Postgres specific intializations/imports are handled.

**Comment by lukehsiao** [comment]
> What all changes are required to make the switch, and, is there an existing config/notes that can help to make the change. From my understanding the Alchemy supports both and we have to just make sure any Postgres specific intializations/imports are handled.

This is correct. Currently, we use postgresql-specific features of sqlachemy that would need to be replaced as well. For example, if you search for `sqlalchemy.dialects import postgresql` you'll see several files which utilize postgres-specific features. We'd need to make sure that there were equivalent features using other backends as well.

**Comment by Prabh06** [comment]
@lukehsiao is this feature in plans or on the roadmap?

**Comment by lukehsiao** [comment]
@Prabh06 We would love to support this. Unfortunately, it's a non-trivial
change. To do it well, we would need to refactor Fonduer so that the library
and the database are significantly more decoupled than they are now. In
general, this is something we would like to accomplish, but don't have a
concrete path to do so yet.

If you have design suggestions, or are able to help contribute some work,
please let us know.

**Comment by SenWu** [comment]
Closing it for now, feel free to reopen.
