### ISSUE TITLE
abs_char_offsets is not absolute but relative

### ISSUE THREAD

**Issue by lauratolosi** [HazyResearch/fonduer#332]
I understand form the documentation that `abs_char_offsets` (https://fonduer.readthedocs.io/en/latest/user/parser.html#fonduer.parser.models.Sentence.abs_char_offsets) should return the absolute character offset from the beginning of the HTML document of the sentence. However, looking at the code and testing on my data, I get that the values are always 0 and never updated during parsing.

**Comment by HiromuHota** [comment]
I couldn't reproduce your issue with v0.7.0 of Fonduer.
What version of Fonduer are you using?

**Comment by HiromuHota** [comment]
OK, now I am able to reproduce it.
I'm using the latest commit (3d5392ccfb092e23ac861bc06815c56374d63b55), but is reproducible on v0.7.0 too.
What I can see is
```
> /Users/hiromu/workspace/fonduer/tests/parser/test_parser.py(120)test_parse_md_details()
-> logger.info(f"Doc: {doc}")
[sent.abs_char_offsets for sent in doc.sentences] 
[[0, 7], [0, 5, 8, 13, 18, 20, 27, 35], [0, 7], [0, 10, 15, 17, 20], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0, 2, 6], [0, 8, 12], [0], [2], [0], [0], [0], [0, 2], [0, 3, 12], [0, 5, 8, 10], [0], [0, 6], [0], [0], [0], [0, 5], [0], [0, 1], [0], [0], [0], [0, 1], [0], [0, 5], [0], [0, 1], [0, 3, 10, 15], [0, 4, 8, 10, 11, 14, 15], [0], [0, 3, 6, 12, 15], [0, 4, 8], [0]]
```
`abs_char_offsets` looks **relative** (to the beginning of the sentence) instead of absolute from the beginning of the document.

In @lauratolosi case, if `abs_char_offsets` is always 0, then each Sentence has only 1 word.

I'd change the issue title to "abs_char_offsets is not absolute but relative"

**Comment by HiromuHota** [comment]
I couldn't trace back when this issue happened. At least this issue existed on v0.5.0, v0.4.0, and v0.3.0. I stopped tracing back at v0.2.2 as I had some compilation error from dependencies.

**Comment by HiromuHota** [comment]
I've almost finished a patch. If tests pass, I submit it.
