### ISSUE TITLE
HTMLDocPreprocessor for PDF documents is it always required

### ISSUE THREAD

**Issue by ashleo25** [HazyResearch/fonduer#521]
I have set of pdf documents but i am struggling with converting them into html documents
I directly want to parse the pdf documents without htmldocpreprocessor in the loop
Please confirm is it possible or way around  Please help @lukehsiao @SenWu @vincentschen @ZZWENG

**Comment by SenWu** [comment]
Hi @ashleo25,

Thanks for your interest in our work.

The short answer is no, since in our current pipeline we need to use the HTML-like document to access the textual, tabular, structural, and visual information in the pdf.

But the good news is that we are working on supporting different ways to convert pdf to HTML which I think will largely benefit real users. As you might know, we currently use Adobe Acrobat to convert pdfs to HTMLs in our tutorials. Alternatively, we now support hOCR (aka HTML OCR) as an input format that can be generated by Tesseract, the most popular open-source OCR tool for pdf. We are also working on [pdftotree](https://github.com/HazyResearch/pdftotree), a tool for converting PDF into hOCR with text, tables, and figures being recognized and preserved which will also be the input in Fonduer.

Stay tuned!

Sen

**Comment by ashleo25** [comment]
Hi @SenWu 
Thanks for sharing the details 
I tried using pdftotree for pdf to HTML conversion but unable to convert images in the pdf 
There was a mention  that --  A full set of documents and ground truth labels can be downloaded here: PaleoDocs. You can train a machine-learning model to extract table regions by downloading this dataset and extracting it into a directory named data and then running the command below.

I tried this and the model pkl that gets generated is 1kb in size and using that also as model parameter did not  helped me as i am not getting images converted to html

I have been able to run fonduer end-to-end its just this piece of pdf to html and specially images is not working for me 
Urgent need of your help @lukehsiao @stephenbach @vincentschen @SenWu @

**Comment by SenWu** [comment]
Hi @ashleo25,

Thanks for raising this issue.

I think it would be better open an issue for [pdftotree repo](https://github.com/HazyResearch/pdftotree). Also, more info or example doc would help us better understand the issue and resolve it.

Sen
